apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: nan-express-app
  app.kubernetes.io/instance: nan-express-app
  app.kubernetes.io/name: nan-express-app